# Use an official node runtime as a parent image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json files first for better caching
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY frontend /app/frontend

# Build the Next.js app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the Next.js app in production mode
CMD ["npm", "start"]